"""Chinese labels for Palantir website secondary navigation."""

TAG_ZH = {
    "Newsroom": "新闻",
    "Insights": "洞察",
    "Events": "活动",
    "Offerings": "行业方案",
    "Platforms": "平台",
    "Impact Studies": "客户案例",
    "Partnerships": "合作伙伴",
    "Careers": "招聘",
    "About": "关于",
    "Privacy & Civil Liberties": "隐私与公民自由",
    "Information Security": "信息安全",
    "Customer Success": "客户成功",
    "Special Products": "特殊产品",
    "Palantir Explained": "Palantir 解析",
    "press-releases": "新闻稿",
    "letters": "公开信",
    "media": "媒体报道",
    "thought-leadership": "思想领导力",
    "announcements": "公告",
    "market-research": "市场研究",
    "industry-insights": "行业洞察",
    "whitepapers": "白皮书",
    "events": "活动",
    "conferences": "会议",
    "developer-events": "开发者活动",
    "classes": "课程",
    "defense": "国防",
    "government": "政府",
    "intelligence": "情报",
    "builders": "构建者",
    "financial-services": "金融服务",
    "healthcare": "医疗",
    "life-sciences": "生命科学",
    "supply-chain": "供应链",
    "energy": "能源",
    "commerce": "零售与消费品",
    "industrial": "工业制造",
    "insurance": "保险",
    "telecommunications": "电信",
    "utilities": "公用事业",
    "ai-solutions": "AI 方案",
    "industry": "行业方案",
    "aip": "AIP",
    "foundry": "Foundry",
    "apollo": "Apollo",
    "gotham": "Gotham",
    "ontology": "本体",
    "sovereign": "主权方案",
    "developer": "开发者",
    "platform-capabilities": "平台能力",
    "customer-stories": "客户案例",
    "partners": "合作伙伴",
    "hiring": "招聘流程",
    "students": "学生与早期人才",
    "engineering": "工程团队",
    "fellowships": "奖学金项目",
    "culture": "企业文化",
    "opportunities": "职位机会",
    "company": "公司",
    "foundation": "基金会",
    "responsibility": "责任承诺",
    "privacy-and-governance": "隐私与治理",
    "security": "安全",
    "services": "服务",
    "products": "产品",
    "series": "系列",
    "2022-annual-letter": "2022 年度公开信",
    "2024-ai-ds-ml-market-study": "2024 AI、数据科学与机器学习市场研究",
    "2024-modelops-market-study": "2024 ModelOps 市场研究",
    "500": "服务器错误",
    "2025-ai-ds-ml-market-study": "2025 AI、数据科学与机器学习市场研究",
    "2025-market-studies": "2025 市场研究",
    "2025-modelops-market-study": "2025 ModelOps 市场研究",
    "2025-wisdom-of-crowds-agentic-ai-market-study": "2025 群体智慧 Agentic AI 市场研究",
    "AIP": "AIP",
    "USG": "USG",
    "accenture": "埃森哲",
    "advisors": "顾问",
    "ai-sovereignty-is-your-alpha": "AI 主权就是你的优势",
    "aip": "AIP",
    "aip-for-asset-maintenance-scheduling": "AIP 资产维护排程",
    "aip-for-ehs-risk-management": "AIP EHS 风险管理",
    "aip-for-maintenance-assistance": "AIP 维护辅助",
    "aip-for-program-knowledge-management": "AIP 项目知识管理",
    "aip-for-public-consultation-analysis": "AIP 公共咨询分析",
    "aip-for-sustainable-solutions": "AIP 可持续解决方案",
    "aip-for-wastewater-system-optimization": "AIP 污水系统优化",
    "aip-for-work-breakdown-structure-creator": "AIP 工作分解结构创建器",
    "aip-now-statement": "AIP Now 声明",
    "aip-sensor-integration-for-wastewater-management": "AIP 污水管理传感器集成",
    "aipcon": "AIPCon",
    "airbus": "空中客车",
    "american-tech-fellowship": "美国技术奖学金",
    "aml-b": "反洗钱 B",
    "anaconda": "Anaconda",
    "anti-money-laundering": "反洗钱",
    "apollo": "Apollo",
    "army-intelligence-data-platform": "陆军情报数据平台",
    "army-vantage": "Army Vantage",
    "attributes": "属性",
    "automotive-mobility": "汽车与出行",
    "aws": "AWS",
    "axel-springer": "Axel Springer",
    "bain": "贝恩",
    "bank-digitization": "银行数字化",
    "beyond-anonymization": "超越匿名化",
    "campaign-optimization": "营销活动优化",
    "cleveland-clinic": "克利夫兰诊所",
    "climate-pledge": "气候承诺",
    "clinical-data-rd": "临床数据研发",
    "cloud": "云",
    "commercial": "商业",
    "compliance-acceleration": "合规加速",
    "concordance": "一致性",
    "construction": "建筑",
    "consumer-goods": "消费品",
    "crypto": "加密资产",
    "customer-retention": "客户留存",
    "data-mesh": "数据网格",
    "data-protection": "数据保护",
    "databricks": "Databricks",
    "defense": "国防",
    "deloitte": "德勤",
    "designing-for-deletion": "为删除而设计",
    "devcon": "DevCon",
    "devcon-archive": "DevCon 往期内容",
    "devcon-on-your-mark": "DevCon On Your Mark",
    "devcon-submit": "DevCon 投稿",
    "devcon3": "DevCon 3",
    "devcon4": "DevCon 4",
    "devcon5": "DevCon 5",
    "developers": "开发者",
    "disaster-response": "灾害响应",
    "downtime-minimization": "停机时间最小化",
    "edge-ai": "边缘 AI",
    "elite": "Elite",
    "end-of-year-message-from-alex-karp": "Alex Karp 年终致辞",
    "energy": "能源",
    "erp": "ERP",
    "explore": "探索",
    "fabrice-bregier-palantir-veut-etre-un-acteur-majeur-de-la-tech-francaise": "Fabrice Bregier：Palantir 希望成为法国科技的重要参与者",
    "federal-health": "联邦医疗",
    "fedstart": "FedStart",
    "financial-services": "金融服务",
    "first-breakfast": "First Breakfast",
    "food-and-beverage": "食品与饮料",
    "foundation": "基金会",
    "foundry": "Foundry",
    "foundry-entity-resolution": "Foundry 实体解析",
    "foundry-explained-get-demo": "Foundry 解析与演示",
    "fujitsu": "富士通",
    "getting-hired": "入职指南",
    "google-cloud": "Google Cloud",
    "gotham": "Gotham",
    "government-web-services": "政府网络服务",
    "guidehouse": "Guidehouse",
    "gxp-solutions": "GxP 解决方案",
    "hannover": "汉诺威",
    "health": "医疗",
    "hyperauto": "Hyperauto",
    "in-defense-of-europe": "为欧洲辩护",
    "infrastructure": "基础设施",
    "insights": "洞察",
    "insurance": "保险",
    "intelligence": "情报",
    "inventory-optimization": "库存优化",
    "iot": "物联网",
    "iot-A": "物联网 A",
    "jacobs": "Jacobs",
    "japan": "日本",
    "impact-or-disaster-response-jpn": "影响力与灾害响应（日本）",
    "interview-with-fabrice-bregier-president-of-palantir-france": "专访 Palantir 法国总裁 Fabrice Bregier",
    "kelly-explains-his-decision-to-join-palantir": "Kelly 解释加入 Palantir 的决定",
    "kindermorgan": "Kinder Morgan",
    "kt": "KT",
    "letters": "公开信",
    "life-at-palantir": "Palantir 的工作与生活",
    "life-sciences": "生命科学",
    "master-classes": "大师课",
    "media": "媒体",
    "meritocracy-fellowship": "精英奖学金",
    "metaconstellation": "MetaConstellation",
    "microsoft": "微软",
    "mixed-reality": "混合现实",
    "ncmec": "国家失踪与受虐儿童中心",
    "nhs-vaccine-rollout-success-built-on-nhs-determination-and-military": "NHS 疫苗接种：建立在 NHS 决心与军方协作上的成功",
    "network-reliability": "网络可靠性",
    "new-homepage": "新版首页",
    "next-best-offer": "下一个最佳offer",
    "ontology": "本体论",
    "open-positions": "在招职位",
    "oracle": "Oracle",
    "pagenotfound": "页面未找到",
    "palantir-ai-ethics": "Palantir AI 伦理",
    "palantir-ai-policy-contributions": "Palantir AI 政策贡献",
    "palantir-for-builders": "面向构建者的 Palantir",
    "palantir-for-hospitals": "面向医院的 Palantir",
    "palantir-for-rail": "面向铁路的 Palantir",
    "palantir-fraud-detection": "Palantir 欺诈检测",
    "palantir-is-not-a-data-company": "Palantir 不是一家数据公司",
    "palantir-is-still-not-a-data-company": "Palantir 仍然不是一家数据公司",
    "palantir-mourns-the-loss-of-sergio-marchionne": "Palantir 悼念 Sergio Marchionne",
    "partner-in-crises": "危机中的伙伴",
    "partners": "合作伙伴",
    "partnership-vanguard": "Vanguard 合作",
    "powering-innovation-for-doosan-infracore": "为斗山工程机械赋能创新",
    "preferred-partners": "优选合作伙伴",
    "press-releases": "新闻稿",
    "pricing-optimization": "定价优化",
    "principles": "原则",
    "privacy-and-civil-liberties-engineering": "隐私与公民自由工程",
    "procurement": "采购",
    "protect-your-sovereignty": "保护你的主权",
    "purpose-based-access-controls": "基于目的的访问控制",
    "pwc": "普华永道",
    "rackspace": "Rackspace",
    "readiness": "战备",
    "responsible-disclosure": "负责任披露",
    "retail": "零售",
    "ringier": "Ringier",
    "rubix": "Rubix",
    "rubix-specs": "Rubix 规格",
    "sales-acceleration": "销售加速",
    "sap": "SAP",
    "security-advisories": "安全公告",
    "security-forge": "Security Forge",
    "semiconductors": "半导体",
    "shipos-atf": "ShipOS ATF",
    "snowflake": "Snowflake",
    "sompo": "Sompo",
    "sonnedix": "Sonnedix",
    "sosa": "SOSA",
    "search": "搜索",
    "sovereign": "Sovereign",
    "sovereignaios": "SovereignAIOS",
    "sovereignaios-modelengine": "SovereignAIOS ModelEngine",
    "students": "学生",
    "students-and-early-talent": "学生与早期人才",
    "supply-chain": "供应链",
    "supply-chain-emissions": "供应链排放",
    "supply-chain-risk-management": "供应链风险管理",
    "swiss-re": "瑞士再保险",
    "tampa-general-hospital": "坦帕总医院",
    "task-prioritization": "任务优先级",
    "team": "团队",
    "technologies": "技术",
    "telecommunications": "电信",
    "thank-you-or-moving-beyond-customer-analytics-whitepaper": "《谢谢，或超越客户分析》白皮书",
    "thought-leadership": "思想领导力",
    "titanium": "Titanium",
    "transaction-monitoring": "交易监控",
    "trust-in-data": "数据信任",
    "turbine-maintenance": "涡轮机维护",
    "twg": "TWG",
    "unit8": "Unit8",
    "unlock": "Unlock",
    "usg-recruitment": "USG 招聘",
    "utilities": "公用事业",
    "vertex-for-energy": "能源版 Vertex",
    "veterans": "退伍军人",
    "warranty-optimization": "保修优化",
    "world-food-programme": "世界粮食计划署",
}
